name: 'Bug report'
# title:
description: Bug report
labels:
  - bug
# assignees:
#   - nefilmjp
body:
  - type: dropdown
    id: os
    attributes:
      label: OS
      multiple: true
      options:
        - Win
        - Mac
        - Linux
        - Android
        - iOS
        - Other
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      multiple: true
      options:
        - Chrome
        - Edge
        - Firefox
        - Safari
        - Other
    validations:
      required: true
  - type: input
    id: env-detail
    attributes:
      label: More information about the environment
      placeholder: Version, device, resolution, etc...
  - type: checkboxes
    id: category
    attributes:
      label: Category
      description: You may select more than one.
      options:
        - label: Portal glyph detection
        - label: UI function
        - label: Visual appearance
        - label: Text/Sentence
        - label: Other/Unknown
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: checkboxes
    id: will-pr
    attributes:
      label: Participation
      options:
        - label: I am willing to create a pull request for this issue.
